market/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls , name="admin"),
    path("" , include("shopping.urls")),
    path("users/" , include("users.urls"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shopping/urls.py
from django.urls import path

from . import views

app_name = "shopping"
urlpatterns = [
    path("" , views.product_list , name="product_list") ,
    path("comment/<int:product_id>/" , views.comments , name="comments") , 
    path("add_comment/<int:product_id>/" , views.add_comment , name="add_comment"),
    path("add_replay/<int:product_id>/<int:comment_id>" , views.add_replay , name="add_replay"),
    path("product_describe/<int:product_id>/" , views.product_describe , name="product_describe"),
    path("buy_list/" , views.buy_list , name="buy_list") ,
    path("buy_action/", views.buy_action , name="buy_action"),
    path("delete_user/<int:product_id>/" , views.delete_user , name="delete_user"),
    path("buy_history/" , views.buy_history , name="buy_history"),
    path("buy_history/" , views.buy_history , name="buy_history"),
    path("admin_panel/" , views.admin_panel , name="admin_panel"),
    path("admin_action/" , views.admin_action , name="admin_action"),
    path("admin_action/<int:product_id>/" , views.delete_admin_product , name="delete"),
    path("admin_history/" , views.admin_history , name="admin_history"), 
    path("like_post/<int:post_id>/" , views.like_post , name="like_post"),
    path("like_comment/<int:comment_id>/<int:product_id>/" , views.like_comment , name="like_comment"),
    path("supporting_page/" , views.supporting_page , name="supporting_page"),
    path("chat_page/" , views.chat_user_page , name="chat_page"),
    path("list_chat_admin/" , views.list_chat_admin , name="list_chat_admin"),
    path("chat_admin_page/<int:user_id>/" , views.chat_admin_page , name="chat_admin_page")
]

users/urls.py
from django.urls import path , include
from . import views

app_name = "users"
urlpatterns  = [
    path("" , include("django.contrib.auth.urls")) ,
    path("register/" , views.register , name="register"),
    path("informations/<int:totall_price>/" , views.fill_profill , name="profill")
]

shopping/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Product(models.Model) :
    name = models.CharField(max_length=20)
    price = models.BigIntegerField()
    picture = models.ImageField()
    likes = models.ManyToManyField(User , blank=True , related_name="like")
    
    def __str__(self):
        return self.name
    
class SizeChoice(models.TextChoices) :
    FULL = "100%" , "100%"
    HALF = "50%" , "50%"
    QUARTER = "25%" , "25%"
    
class ColorChoice(models.TextChoices) :
    RED = "red" , "red"
    GREEN = "green" , "green"
    BLUE = "blue" , "blue"
    BLACK = "black" , "black"
    WHITE = "white" , "white"
    BROWN = "brown" , "brown"
    SILVER = "silver" , "silver"
    
class Order(models.Model) :
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product , on_delete=models.CASCADE , related_name="prod")
    date_added = models.DateTimeField(auto_now_add=True)
    count = models.PositiveSmallIntegerField(default=0)
    size = models.CharField(choices=SizeChoice.choices , default=SizeChoice.FULL , max_length=100)
    color = models.CharField(choices=ColorChoice.choices , default=ColorChoice.BROWN , max_length=100)
    recieve_code = models.BigIntegerField(default=0)
    count_history = models.PositiveSmallIntegerField(default=0)
    level1 = models.BooleanField(default=False)
    level2 = models.BooleanField(default=False)
    level3 = models.BooleanField(default=False)
    shows = models.SmallIntegerField(default=0)
    date_added = models.CharField(max_length=100)
    date_deleted = models.CharField(max_length=100)
    
class Comments(models.Model) :
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    text = models.TextField()
    likes = models.ManyToManyField(User , blank=True , related_name="like_commnet")
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.text[:50]}..."

class Replay(models.Model) :
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    comment = models.ForeignKey(Comments , on_delete=models.CASCADE , related_name="replay")
    text = models.TextField()
    likes = models.IntegerField(default=0 )
    date_added = models.DateTimeField(auto_now_add=True )
    
    def __str__(self):
        return f"{self.text[:50]}..."
    
class ChatUser(models.Model) :
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    
class Chat(models.Model) :
    sender = models.ForeignKey(User , on_delete=models.CASCADE , related_name="sender")
    receiver = models.ForeignKey(User , on_delete=models.CASCADE , related_name="receiver")
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    admin_read = models.BooleanField(default=False)
    user_read = models.BooleanField(default=False)

    def __str__(self):
        return self.text

shopping/views.py
from django.shortcuts import render ,get_object_or_404, redirect
from django.db.models import Q , Count
from .form import CommentAdded , ReplayAdded , AddToBuyPage , AddProduct  , Chats
from .models import Product , Comments , Order , Chat , ChatUser , User
from random import choice
import jdatetime
from users.models import Acount
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator
# Create your views here.

def product_list(request) :
    product = Product.objects.all()
    paginator = Paginator(product, 12)  # 12 محصول در هر صفحه

    page_number = request.GET.get('page')  # شماره صفحه از URL
    page_obj = paginator.get_page(page_number)
    context = {"product" : page_obj }
    return render(request , "shopping/product_list.html" , context)
    
def product_describe(request , product_id) :
    product = Product.objects.get(id = product_id)
    try :
        order = Order.objects.get(user = request.user,
                                  product = product)
    except Order.DoesNotExist :
        order = Order(user = request.user , 
                      product = product)
    if request.method != "POST" :
        form = AddToBuyPage(instance=order)
    else :
        form = AddToBuyPage(instance=order, data=request.POST)
        if form.is_valid() :
            form.save()
            return redirect("shopping:product_describe" , product_id = product_id)
    context = {"form" : form , "product" : product , "pro_ord" : order}
    return render(request , "shopping/product_describe.html" , context)

def comments(request , product_id) :
    product = Product.objects.get(id = product_id)
    comments = product.comments_set.order_by("date_added")
    context = {"product" : product , "comments" : comments}
    return render(request , "shopping/comments.html" , context)

def add_comment(request , product_id) :
    product = Product.objects.get(id = product_id)
    if request.method != "POST" :
        form = CommentAdded()
    else :
        form = CommentAdded(data=request.POST)
        if form.is_valid() :
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.product = product
            new_comment.save()
            return redirect("shopping:comments" , product_id = product_id)
    
    context = {"form" : form , "product" : product}
    return render(request , "shopping/add_comment.html" , context)

def add_replay(request , comment_id , product_id) :
    product = Product.objects.get(id = product_id)
    comment = Comments.objects.get(id = comment_id)
    if request.method != "POST" :
        form = ReplayAdded()
    else :
        form = ReplayAdded(data=request.POST)
        if form.is_valid() :
            new_replay = form.save(commit=False)
            new_replay.comment = comment
            new_replay.user = request.user
            new_replay.save()
            return redirect("shopping:comments" ,product_id = product_id )
    
    context = {"form" : form , "comment" : comment , "product" : product}
    return render(request , "shopping/add_replay.html" , context)

def buy_list(request) :
    order = Order.objects.filter(user = request.user ,count__gt = 0)
    totall_price = 0
    for pro in order :
        pro.level1 = True
        totall_price += pro.count * pro.product.price
        pro.save()
    context = {"order" : order , "totall_price" : totall_price}
    return render(request , "shopping/buy_list.html" , context)

def buy_action(request) :
    numbers = list(n for n in range(10))
    order = Order.objects.filter(user = request.user , level2 = True)
    revieve_code = ""
    for x in range(8) :
        num = choice(numbers)
        revieve_code += str(num)
    for pro in order :
        if pro.recieve_code == 0 :
            pro.recieve_code = revieve_code
            pro.date_added = f"{jdatetime.datetime.now().strftime('%Y/%m/%d : %H')}"
            pro.shows = 1
            pro.save()
    context = {"order" : order}
    return render(request , "shopping/buy_action.html" , context)

def delete_user(request , product_id) :
    order = Order.objects.get(id = product_id)
    if request.method != "POST" :
        order.level2 = False
        order.level3 = True
        order.shows = 3
        order.date_deleted= f"{jdatetime.datetime.now().strftime('%Y/%m/%d : %H')}"
        order.save()
        return redirect("shopping:buy_action")

def buy_history(request) :
    order = Order.objects.order_by("-date_deleted").filter(user = request.user , level3 = True)
    context = {"order" : order}
    return render(request , "shopping/buy_history.html" , context)

def is_admin(user) :
    return user.is_superuser

@user_passes_test(is_admin)
def admin_panel(request) :
    if request.method != "POST" :
        form = AddProduct()
    else :
        form = AddProduct(request.POST , request.FILES)
        if form.is_valid() :
            form.save()
            return redirect("shopping:product_list")

    context = {"form" : form}
    return render(request , "shopping/admin_panel.html" , context)
    
def admin_action(request) :
    acount = Acount.objects.all()
    order = Order.objects.order_by( "shows","-date_added").filter(level2 = True)
    context = {"order" : order , "acount" : acount}
    return render(request , "shopping/admin_action.html" , context)

def admin_history(request) :
    acount = Acount.objects.all()
    order = Order.objects.order_by("-date_deleted").filter(level3 = True)
    context = {"acount" : acount , "order" : order}
    return render(request , "shopping/admin_history.html" , context)

def delete_admin_product(request , product_id) :
    order = Order.objects.get(id = product_id)
    if request.method != "POST" :
        order.level3 = False
        order.level2 = True
        order.shows = 3
        order.save()
    return redirect("shopping:admin_action")

def like_post(request, post_id) :
    like = get_object_or_404(Product , id = post_id)
    if request.user in like.likes.all() :
        like.likes.remove(request.user)
    else :
        like.likes.add(request.user)
    return redirect("shopping:product_list")

def like_comment(request , comment_id , product_id) :
    like = get_object_or_404(Comments , id = comment_id)
    product = get_object_or_404(Product , id = product_id)
    if request.user in like.likes.all() :
        like.likes.remove(request.user)
    else :
        like.likes.add(request.user)

    return redirect("shopping:comments" , product_id = product_id)

def supporting_page(request) :
    return render(request , "shopping/supporting_page.html")

def chat_user_page(request) :
    admin = User.objects.get(is_superuser = True)
    if request.method != "POST" :
        form = Chats()
    else :
        form = Chats(data=request.POST) 
        if form.is_valid() :
            new_text = form.save(commit=False)
            new_text.sender = request.user
            new_text.receiver = admin
            form.save()
            return redirect("shopping:chat_page")
        
    chats = Chat.objects.filter(sender = request.user , receiver = admin) | Chat.objects.filter(sender = admin , receiver = request.user)
    chats = chats.order_by("-date_added")
    for chat in chats :
        if chat.receiver == request.user :
            chat.user_read = True
            chat.save()
    context = {"chats" : chats , "form" : form}
    return render(request , "shopping/chat_page.html" , context)

def list_chat_admin(request) :
    users = User.objects.exclude(is_superuser = True)
    users = users.annotate(unread_count = Count("sender" ,
    filter=Q(sender__receiver=request.user,
    sender__admin_read = False))).order_by("-unread_count")
    
    context = {"users" : users }
    return render(request , "shopping/list_chat_admin.html" , context)

def chat_admin_page(request , user_id) :
    user = User.objects.get(id = user_id)
    if request.method != "POST" :
        form = Chats()
    else :
        form = Chats(data=request.POST)
        if form.is_valid() :
            new_text = form.save(commit=False)
            new_text.sender = request.user
            new_text.receiver = user
            form.save()
            return redirect("shopping:chat_admin_page" , user_id = user_id)
    
    chats = Chat.objects.filter(sender = request.user , receiver = user) | Chat.objects.filter(sender = user , receiver = request.user)
    chats = chats.order_by("-date_added")
    for chat in chats :
        if chat.receiver == request.user :
            chat.admin_read = True
            chat.save()
    context = {"chats" : chats , "form" : form , "userr" : user}
    return render(request , "shopping/chat_admin_page.html" , context)

shopping/templates/shopping/add_comment.html
{% extends "shopping/base.html" %}
{% block content %}
{% load static %}
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gognoos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
<p style="margin-left: 40px;">Add new comment :</p>
<div style=" justify-items: center;">
<form action="{% url 'shopping:add_comment' product.id %}" , method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-success">Add comment</button>
    {% endbuttons %}
</form>    
  </body>
</div>


{% endblock content %}

shopping/templates/shopping/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gognoos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
  </head>
  <body>
<nav class="navbar " style="background-color:#f7deb1; margin-left: 3vw;
 margin-right: 3vw; margin-top: 10px; margin-bottom: 20px;">
  <div class="container-fluid">
    <a href="{% url 'shopping:product_list' %}"><i class="bi bi-house-door-fill">
  <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="#198735" class="bi bi-house-door-fill" viewBox="0 0 16 16">
  <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5"/>
</svg>
    </i></a>
    {% if user.is_superuser %}
    <a href="{% url 'shopping:list_chat_admin' %}"><i class="bi bi-headset">
      <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="#198735" class="bi bi-headset" viewBox="0 0 16 16">
  <path d="M8 1a5 5 0 0 0-5 5v1h1a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V6a6 6 0 1 1 12 0v6a2.5 2.5 0 0 1-2.5 2.5H9.366a1 1 0 0 1-.866.5h-1a1 1 0 1 1 0-2h1a1 1 0 0 1 .866.5H11.5A1.5 1.5 0 0 0 13 12h-1a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1h1V6a5 5 0 0 0-5-5"/>
</svg>
    </i></a>
    <a href="{% url 'shopping:admin_panel' %}"><i class="bi bi-sliders2">
      <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="#198735" class="bi bi-sliders2" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M10.5 1a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V4H1.5a.5.5 0 0 1 0-1H10V1.5a.5.5 0 0 1 .5-.5M12 3.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m-6.5 2A.5.5 0 0 1 6 6v1.5h8.5a.5.5 0 0 1 0 1H6V10a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5M1 8a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2A.5.5 0 0 1 1 8m9.5 2a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V13H1.5a.5.5 0 0 1 0-1H10v-1.5a.5.5 0 0 1 .5-.5m1.5 2.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5"/>
</svg>
    </i></a>
    {% endif %}
    {% if user.is_authenticated %}
    {% if not user.is_superuser %}
    <a href="{% url 'shopping:buy_list' %}"><i class="bi bi-basket-fill">
    <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="#198735" class="bi bi-basket-fill" viewBox="0 0 16 16">
    <path d="M5.071 1.243a.5.5 0 0 1 .858.514L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5H15v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9H.5a.5.5 0 0 1-.5-.5v-2A.5.5 0 0 1 .5 6h1.717zM3.5 10.5a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0z"/>
    </svg>
    </i></a>
    <a href="{% url 'shopping:chat_page' %}"><i class="bi bi-headset">
      <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="#198735" class="bi bi-headset" viewBox="0 0 16 16">
  <path d="M8 1a5 5 0 0 0-5 5v1h1a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V6a6 6 0 1 1 12 0v6a2.5 2.5 0 0 1-2.5 2.5H9.366a1 1 0 0 1-.866.5h-1a1 1 0 1 1 0-2h1a1 1 0 0 1 .866.5H11.5A1.5 1.5 0 0 0 13 12h-1a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1h1V6a5 5 0 0 0-5-5"/>
</svg>
    </i></a>
    {% endif %}
    {% endif %}
    <a class="navbar-brand me-0" ><i class="bi bi-list" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight">
    <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="#198735"
    class="bi bi-list" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
    </svg></i></a>
  </div>
</nav>
    
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight"
style="width: 50vw; max-width: 250px;" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <h5 id="offcanvasRightLabel">Menu</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"></button>
  </div>
  <div class="offcanvas-body">
    <ul class="list-unstyled">
      {% if user.is_authenticated %}
      <li class="text-decoration-none d-block mb-2">Hello ,{{user.username}}.</li>
      {% endif %}
      <li><a href="{% url 'shopping:product_list' %}" class="text-decoration-none d-block mb-2">Home</a></li>
      {% if user.is_superuser %}
      <li><a href="{% url 'shopping:list_chat_admin' %}" class="text-decoration-none d-block mb-2">Supporting</a></li>
      <li><a href="{% url 'shopping:admin_panel' %}" class="text-decoration-none d-block mb-2">Admin panel</a></li>
      {% endif %}
      {% if user.is_authenticated %}
      {% if not user.is_superuser %}
      <li><a href="{% url 'shopping:buy_list' %}" class="text-decoration-none d-block mb-2">Buy page</a></li>
      <li><a href="{% url 'shopping:chat_page' %}" class="text-decoration-none d-block mb-2">Supporting</a></li>
      {% endif %}
      <form action="{% url 'users:logout' %}" method="post">
        {% csrf_token %}
        <button name="submit" class="btn btn-primary" >Log out</button>
      </form>
      {% else %}
      <li><a href="{% url 'users:login' %}" class="text-decoration-none d-block mb-2">Login</a></li>
      <li><a href="{% url 'users:register' %}" class="text-decoration-none d-block mb-2">Register</a></li>
      {% endif %}
    </ul>
  </div>
</div>
{% block content %}{% endblock content %}
  </body>
</html>

shopping/templates/shopping/comments.html
{% extends "shopping/base.html" %}
{% block content %}
{% load static %}
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gognoos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <h5 class="card-body display-6" style="margin-left: 40px;">{{product.name}}:</h5>
    {% if user.is_authenticated %}
    <p style="margin-left: 40px;"><a class="text-decoration-none" href="{% url 'shopping:add_comment' product.id %}">Add comment</a></p>
    {% else %}
<p><a href="{% url 'users:login' %}">Add comment</a></p>
{% endif %}
<ul>
    {% for com in comments %}
    <li class="text-decoration-none d-block" >
        <div class="alert alert-info d-lg-block" style="margin-right: 3vw; background-color: #7ebe77;">
            <div class="accordion accordion-flush" id="accordionFlushExample{{com.id}}">
                <h5>{{com.user.username}}:</h5>
                <p style="margin-top: 25px;">{{com.text}}</p>
                <p>Like : {{com.likes.count}}</p>
                <div style="display: flex;">
                    {% if user.is_authenticated %}
                    {% if user in com.likes.all %}
                    <div>
                        <a href="{% url 'shopping:like_comment' com.id product.id %}"><i class="bi bi-heart-fill">
                            <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
                            </svg>
                        </i></a>    
                    </div>
                    {% else %}
                    <div>
                        <a href="{% url 'shopping:like_comment' com.id product.id %}"><i class="bi bi-heart">
                            <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="red" class="bi bi-heart" viewBox="0 0 16 16">
                            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                            </svg>
                        </i></a>    
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'shopping:add_replay' product.id com.id %}" style="margin-left: 30px;"><i class="bi bi-reply-fill">
                            <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor" class="bi bi-reply-fill" viewBox="0 0 16 16">
                            <path d="M5.921 11.9 1.353 8.62a.72.72 0 0 1 0-1.238L5.921 4.1A.716.716 0 0 1 7 4.719V6c1.5 0 6 0 7 8-2.5-4.5-7-4-7-4v1.281c0 .56-.606.898-1.079.62z"/>
                            </svg>
                            </i></a></p>    
                    </div>
                    {% endif %}    
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{com.id}}" aria-expanded="false" aria-controls="flush-collapse{{com.id}}">
                        Replays
                        </button>
                    </h2>
                    <div id="flush-collapse{{com.id}}" class="accordion-collapse collapse">
                        <div class="accordion-body">
                            {% for rep in com.replay.all %}
                                <div class="alert alert-info d-lg-block" style="margin-right: 3vw; background-color: #7ebe77 ">
                                    <div class="accordion accordion-flush" id="accordionFlushExample{{ com.id }}">
                                        <h5>{{rep.user.username}}:</h5>
                                        <p style="margin-top: 25px;">{{rep.text}}</p>
                                        <div style="display: flex;">
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    </li>
    {% empty %}
    <p>nothing</p>
    {% endfor %}
    </ul>
</body>

{% endblock content %}